import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import "./prooflogs.css";

interface LogStatus {
  dashboard_html: boolean;
  history_html: boolean;
  orchestration_json: boolean;
  orchestration_html: boolean;
  firecracker_html: boolean;
}

interface FullSystemStatus {
  worker_root: string;
  logs: LogStatus;
}

async function copyToClipboard(text: string) {
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      alert("Path copied to clipboard");
    } else {
      alert("Clipboard API not available.");
    }
  } catch (e) {
    console.error("Clipboard error:", e);
  }
}

export default function ProofLogs() {
  const [scan, setScan] = useState<FullSystemStatus | null>(null);

  useEffect(() => {
    invoke("get_full_system_scan")
      .then((res) => setScan(res as FullSystemStatus))
      .catch((err) => console.error("SCAN ERR:", err));
  }, []);

  if (!scan) {
    return (
      <div className="prooflogs-page">
        <p>Loading proof logs…</p>
      </div>
    );
  }

  const maskedRoot =
    scan.worker_root === "unknown" ? "unknown" : "NIGHTCORE_WORKER";

  async function openProof(path: string) {
    try {
      await invoke("open_path_universal", { path });
    } catch (e) {
      console.error("OPEN ERR:", e);
    }
  }

  async function exportProof(paths: string[]) {
    try {
      const ok = await invoke("export_zip", { paths });
      if (!ok) return;
      alert("ZIP export coming soon.");
    } catch (e) {
      console.error("ZIP ERR:", e);
    }
  }

  return (
    <div className="prooflogs-page">
      <h2>Proof Logs</h2>
      <p className="proof-intro">
        Night Core proof surfaces generated by the worker — dashboards, JSON
        reports, and Firecracker proof logs.
      </p>

      <div className="proof-grid">

        {/* Run Dashboard */}
        <div className={`proof-card ${scan.logs.dashboard_html ? "ok" : "bad"}`}>
          <div className="proof-header">
            <h3>Run Dashboard</h3>
            <div className="short-path">nightcore_dashboard.html</div>
          </div>

          <p className="path">
            {maskedRoot}/logs/nightcore_dashboard.html
          </p>

          <p className={scan.logs.dashboard_html ? "ok" : "bad"}>
            {scan.logs.dashboard_html ? "✔ Exists" : "✘ Missing"}
          </p>

          <div className="proof-actions">
            <button
              disabled={!scan.logs.dashboard_html}
              onClick={() =>
                openProof(scan.worker_root + "/logs/nightcore_dashboard.html")
              }
            >
              Open
            </button>

            <button
              disabled={!scan.logs.dashboard_html}
              onClick={() =>
                exportProof([
                  scan.worker_root + "/logs/nightcore_dashboard.html",
                ])
              }
            >
              Export
            </button>

            <button
              className="copy-btn"
              onClick={() =>
                copyToClipboard(
                  `${scan.worker_root}/logs/nightcore_dashboard.html`
                )
              }
            >
              Copy path
            </button>
          </div>
        </div>

        {/* History Ledger */}
        <div className={`proof-card ${scan.logs.history_html ? "ok" : "bad"}`}>
          <div className="proof-header">
            <h3>History Ledger</h3>
            <div className="short-path">nightcore_history_dashboard.html</div>
          </div>

          <p className="path">
            {maskedRoot}/logs/nightcore_history_dashboard.html
          </p>

          <p className={scan.logs.history_html ? "ok" : "bad"}>
            {scan.logs.history_html ? "✔ Exists" : "✘ Missing"}
          </p>

          <div className="proof-actions">
            <button
              disabled={!scan.logs.history_html}
              onClick={() =>
                openProof(
                  scan.worker_root + "/logs/nightcore_history_dashboard.html"
                )
              }
            >
              Open
            </button>

            <button
              disabled={!scan.logs.history_html}
              onClick={() =>
                exportProof([
                  scan.worker_root + "/logs/nightcore_history_dashboard.html",
                ])
              }
            >
              Export
            </button>

            <button
              className="copy-btn"
              onClick={() =>
                copyToClipboard(
                  `${scan.worker_root}/logs/nightcore_history_dashboard.html`
                )
              }
            >
              Copy path
            </button>
          </div>
        </div>

        {/* Orchestration Dashboard */}
        <div
          className={`proof-card ${
            scan.logs.orchestration_html ? "ok" : "bad"
          }`}
        >
          <div className="proof-header">
            <h3>Orchestration Dashboard</h3>
            <div className="short-path">orchestration_dashboard.html</div>
          </div>

          <p className="path">
            {maskedRoot}/logs/orchestration_dashboard.html
          </p>

          <p className={scan.logs.orchestration_html ? "ok" : "bad"}>
            {scan.logs.orchestration_html ? "✔ Exists" : "✘ Missing"}
          </p>

          <div className="proof-actions">
            <button
              disabled={!scan.logs.orchestration_html}
              onClick={() =>
                openProof(
                  scan.worker_root + "/logs/orchestration_dashboard.html"
                )
              }
            >
              Open
            </button>

            <button
              disabled={!scan.logs.orchestration_html}
              onClick={() =>
                exportProof([
                  scan.worker_root + "/logs/orchestration_dashboard.html",
                ])
              }
            >
              Export
            </button>

            <button
              className="copy-btn"
              onClick={() =>
                copyToClipboard(
                  `${scan.worker_root}/logs/orchestration_dashboard.html`
                )
              }
            >
              Copy path
            </button>
          </div>
        </div>

        {/* Orchestration JSON */}
        <div
          className={`proof-card ${
            scan.logs.orchestration_json ? "ok" : "bad"
          }`}
        >
          <div className="proof-header">
            <h3>Orchestration JSON</h3>
            <div className="short-path">orchestration_report.json</div>
          </div>

          <p className="path">
            {maskedRoot}/logs/orchestration_report.json
          </p>

          <p className={scan.logs.orchestration_json ? "ok" : "bad"}>
            {scan.logs.orchestration_json ? "✔ Exists" : "✘ Missing"}
          </p>

          <div className="proof-actions">
            <button
              disabled={!scan.logs.orchestration_json}
              onClick={() =>
                openProof(
                  scan.worker_root + "/logs/orchestration_report.json"
                )
              }
            >
              Open
            </button>

            <button
              disabled={!scan.logs.orchestration_json}
              onClick={() =>
                exportProof([
                  scan.worker_root + "/logs/orchestration_report.json",
                ])
              }
            >
              Export
            </button>

            <button
              className="copy-btn"
              onClick={() =>
                copyToClipboard(
                  `${scan.worker_root}/logs/orchestration_report.json`
                )
              }
            >
              Copy path
            </button>
          </div>
        </div>

        {/* Firecracker Proof */}
        <div
          className={`proof-card firecracker ${
            scan.logs.firecracker_html ? "ok" : "bad"
          }`}
        >
          <div className="proof-header">
            <h3>Firecracker Proof Log</h3>
            <div className="short-path">nightcore_proof.html</div>
          </div>

          <p className="path">{maskedRoot}/logs/nightcore_proof.html</p>

          <p className={scan.logs.firecracker_html ? "ok" : "bad"}>
            {scan.logs.firecracker_html ? "✔ Exists" : "✘ Missing"}
          </p>

          <div className="proof-actions">
            <button
              disabled={!scan.logs.firecracker_html}
              onClick={() =>
                openProof(scan.worker_root + "/logs/nightcore_proof.html")
              }
            >
              Open
            </button>

            <button
              disabled={!scan.logs.firecracker_html}
              onClick={() =>
                exportProof([
                  scan.worker_root + "/logs/nightcore_proof.html",
                ])
              }
            >
              Export
            </button>

            <button
              className="copy-btn"
              onClick={() =>
                copyToClipboard(
                  `${scan.worker_root}/logs/nightcore_proof.html`
                )
              }
            >
              Copy path
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
